"""
Tests for the StyledHTMLExporter class.

Note on Implementation:
    The current implementation generates CSS rules (e.g., #cell-0, #cell-0-input,
    #cell-0-output) and injects them into the HTML <head> section. However, the
    actual HTML body generated by nbconvert's default templates does NOT include
    elements with these IDs.

    This means the CSS rules have no effect on the output. To make the styles
    functional, the exporter would need to:
    1. Override the cell template to add the appropriate id attributes to cell
       container elements
    2. Create a custom Jinja2 template that includes these IDs in the rendered HTML

    These tests verify that the CSS is correctly generated and injected, but they
    cannot verify that the styles are actually applied to elements since those
    elements don't currently have the matching IDs.
"""

import os
import re
import tempfile

import nbformat as nbf
from bs4 import BeautifulSoup
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from jupyter_export_html_style import StyledHTMLExporter

# Test image data: 1x1 red pixel PNG (89 50 4E 47 = PNG signature)
# This is a minimal valid PNG file for testing purposes
TEST_IMAGE_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
    "0000000d49444154789c63f8cfc03f00050201055fc8f1d20000000049454e44ae426082"
)


def _parse_html(html_string):
    """Parse HTML string and return BeautifulSoup object.

    Args:
        html_string (str): HTML content to parse.

    Returns:
        (BeautifulSoup): Parsed HTML document.
    """
    return BeautifulSoup(html_string, "html.parser")


def _extract_css_rules(html_string):
    """Extract CSS rules from HTML style blocks.

    Args:
        html_string (str): HTML content containing style blocks.

    Returns:
        (dict): Dictionary mapping CSS selectors to their style properties.
            For example: {"#cell-0": {"background-color": "#f0f0f0"}}
    """
    soup = _parse_html(html_string)
    css_rules = {}

    # Find all style tags
    for style_tag in soup.find_all("style"):
        style_content = style_tag.string
        if style_content:
            # Parse CSS rules using regex
            # Matches patterns like: #cell-0 { background-color: #fff; padding: 10px }
            rule_pattern = r"([#.\w-]+)\s*\{([^}]+)\}"
            for match in re.finditer(rule_pattern, style_content):
                selector = match.group(1).strip()
                properties_str = match.group(2).strip()

                # Parse individual properties
                properties = {}
                for prop in properties_str.split(";"):
                    prop = prop.strip()
                    if ":" in prop:
                        key, value = prop.split(":", 1)
                        properties[key.strip()] = value.strip()

                css_rules[selector] = properties

    return css_rules


def _create_notebook_with_image(tmpdir, image_filename="test.png"):
    """Helper function to create a test notebook with an image reference.

    Args:
        tmpdir (str): Temporary directory path.
        image_filename (str): Name of the image file. Defaults to "test.png".

    Returns:
        (str): Path to the created notebook file.
    """
    # Create image file
    img_path = os.path.join(tmpdir, image_filename)
    with open(img_path, "wb") as f:
        f.write(TEST_IMAGE_PNG)

    # Create notebook with markdown cell referencing the image
    nb = new_notebook()
    md_cell = new_markdown_cell(f"![Test Image]({image_filename})")
    nb.cells.append(md_cell)

    # Write notebook to file
    nb_path = os.path.join(tmpdir, "test.ipynb")
    with open(nb_path, "w") as f:
        nbf.write(nb, f)

    return nb_path


def test_styled_html_exporter_initialization():
    """Test that StyledHTMLExporter can be initialized."""
    exporter = StyledHTMLExporter()
    assert exporter.template_name == "classic"


def test_export_notebook_without_styles():
    """Test exporting a notebook without style metadata."""
    exporter = StyledHTMLExporter()

    nb = new_notebook(cells=[new_code_cell("print('hello')"), new_markdown_cell("# Title")])

    output, resources = exporter.from_notebook_node(nb)

    assert output is not None
    assert isinstance(output, str)
    assert len(output) > 0


def test_export_notebook_with_styles():
    """Test exporting a notebook with style metadata."""
    exporter = StyledHTMLExporter()

    cell = new_code_cell("print('styled')")
    cell.metadata["style"] = {"background-color": "#f0f0f0"}

    nb = new_notebook(cells=[cell])

    output, resources = exporter.from_notebook_node(nb)

    assert output is not None
    assert isinstance(output, str)

    # Parse HTML and extract CSS rules
    soup = _parse_html(output)
    css_rules = _extract_css_rules(output)

    # Verify that custom style block exists
    style_tags = soup.find_all("style")
    assert len(style_tags) > 0, "No style tags found in HTML"

    # Check for the custom cell styles comment
    has_custom_comment = False
    for style_tag in style_tags:
        if style_tag.string and "Custom cell styles" in style_tag.string:
            has_custom_comment = True
            break
    assert has_custom_comment, "Custom cell styles comment not found"

    # Verify the specific CSS rule exists with correct property
    assert "#cell-0" in css_rules, "CSS rule for #cell-0 not found"
    assert "background-color" in css_rules["#cell-0"], "background-color property not found"
    assert css_rules["#cell-0"]["background-color"] == "#f0f0f0"


def test_generate_style_block_with_dict():
    """Test generating style block from dictionary styles."""
    exporter = StyledHTMLExporter()

    styles = {"cell-0": {"background-color": "#fff", "padding": "10px"}, "cell-1": {"color": "red"}}

    style_block = exporter._generate_style_block(styles)

    # Parse the generated style block
    css_rules = _extract_css_rules(style_block)

    # Verify structure
    assert "<style>" in style_block
    assert "</style>" in style_block

    # Verify specific CSS rules
    assert "#cell-0" in css_rules
    assert "#cell-1" in css_rules

    # Check properties for cell-0
    assert "background-color" in css_rules["#cell-0"]
    assert css_rules["#cell-0"]["background-color"] == "#fff"
    assert "padding" in css_rules["#cell-0"]
    assert css_rules["#cell-0"]["padding"] == "10px"

    # Check properties for cell-1
    assert "color" in css_rules["#cell-1"]
    assert css_rules["#cell-1"]["color"] == "red"


def test_generate_style_block_with_string():
    """Test generating style block from string styles."""
    exporter = StyledHTMLExporter()

    styles = {"cell-0": "background-color: #eee; padding: 5px;"}

    style_block = exporter._generate_style_block(styles)

    # Parse the generated style block
    css_rules = _extract_css_rules(style_block)

    # Verify structure
    assert "<style>" in style_block

    # Verify specific CSS rule and properties
    assert "#cell-0" in css_rules
    assert "background-color" in css_rules["#cell-0"]
    assert css_rules["#cell-0"]["background-color"] == "#eee"
    assert "padding" in css_rules["#cell-0"]
    assert css_rules["#cell-0"]["padding"] == "5px"


def test_generate_style_block_empty():
    """Test generating style block with no styles."""
    exporter = StyledHTMLExporter()

    styles = {}

    style_block = exporter._generate_style_block(styles)

    assert style_block == ""


def test_export_with_custom_template():
    """Test exporting with a custom template name."""
    exporter = StyledHTMLExporter()
    exporter.template_name = "lab"

    nb = new_notebook(cells=[new_code_cell("x = 1")])

    # This should not raise an error even if template doesn't exist
    # (nbconvert will handle template resolution)
    try:
        output, resources = exporter.from_notebook_node(nb)
        assert output is not None
    except Exception:
        # Template might not exist, which is okay for this test
        pass


def test_export_notebook_with_input_style():
    """Test exporting a notebook with input-style metadata."""
    exporter = StyledHTMLExporter()

    cell = new_code_cell("x = 1")
    cell.metadata["input-style"] = {"background-color": "#ffe"}

    nb = new_notebook(cells=[cell])

    output, resources = exporter.from_notebook_node(nb)

    # Parse and extract CSS rules
    css_rules = _extract_css_rules(output)

    # Verify the CSS rule for input styling
    assert output is not None
    assert "#cell-0-input" in css_rules, "CSS rule for #cell-0-input not found"
    assert "background-color" in css_rules["#cell-0-input"]
    assert css_rules["#cell-0-input"]["background-color"] == "#ffe"


def test_export_notebook_with_output_style():
    """Test exporting a notebook with output-style metadata."""
    exporter = StyledHTMLExporter()

    cell = new_code_cell("print('output')")
    cell.metadata["output-style"] = {"border": "2px solid blue"}

    nb = new_notebook(cells=[cell])

    output, resources = exporter.from_notebook_node(nb)

    # Parse and extract CSS rules
    css_rules = _extract_css_rules(output)

    # Verify the CSS rule for output styling
    assert output is not None
    assert "#cell-0-output" in css_rules, "CSS rule for #cell-0-output not found"
    assert "border" in css_rules["#cell-0-output"]
    assert css_rules["#cell-0-output"]["border"] == "2px solid blue"


def test_export_notebook_with_all_cell_styles():
    """Test exporting a notebook with cell, input, and output styles."""
    exporter = StyledHTMLExporter()

    cell = new_code_cell("y = 2")
    cell.metadata["style"] = {"padding": "10px"}
    cell.metadata["input-style"] = {"color": "red"}
    cell.metadata["output-style"] = {"font-weight": "bold"}

    nb = new_notebook(cells=[cell])

    output, resources = exporter.from_notebook_node(nb)

    # Parse and extract CSS rules
    css_rules = _extract_css_rules(output)

    # Verify all CSS rules are present
    assert output is not None
    assert "#cell-0" in css_rules, "CSS rule for #cell-0 not found"
    assert "#cell-0-input" in css_rules, "CSS rule for #cell-0-input not found"
    assert "#cell-0-output" in css_rules, "CSS rule for #cell-0-output not found"

    # Verify specific properties
    assert css_rules["#cell-0"]["padding"] == "10px"
    assert css_rules["#cell-0-input"]["color"] == "red"
    assert css_rules["#cell-0-output"]["font-weight"] == "bold"


def test_export_notebook_with_notebook_level_style():
    """Test exporting a notebook with notebook-level style metadata."""
    exporter = StyledHTMLExporter()

    nb = new_notebook(cells=[new_code_cell("z = 3")])
    nb.metadata["style"] = ".custom-class { color: green; }"

    output, resources = exporter.from_notebook_node(nb)

    # Parse HTML
    soup = _parse_html(output)

    # Verify notebook-level styles are present
    assert output is not None

    # Check for the custom notebook styles comment
    has_custom_comment = False
    for style_tag in soup.find_all("style"):
        if style_tag.string and "Custom notebook styles" in style_tag.string:
            has_custom_comment = True
            # Also verify the actual style content
            assert ".custom-class { color: green; }" in style_tag.string
            break

    assert has_custom_comment, "Custom notebook styles comment not found"


def test_export_notebook_with_stylesheet():
    """Test exporting a notebook with stylesheet metadata."""
    exporter = StyledHTMLExporter()

    nb = new_notebook(cells=[new_code_cell("a = 4")])
    nb.metadata["stylesheet"] = "https://example.com/style.css"

    output, resources = exporter.from_notebook_node(nb)

    # Parse HTML and find link tags
    soup = _parse_html(output)

    assert output is not None

    # Find the stylesheet link
    link_tags = soup.find_all("link", rel="stylesheet")
    stylesheet_urls = [link.get("href") for link in link_tags]

    assert "https://example.com/style.css" in stylesheet_urls, "Stylesheet link not found in HTML"


def test_export_notebook_with_multiple_stylesheets():
    """Test exporting a notebook with multiple stylesheets."""
    exporter = StyledHTMLExporter()

    nb = new_notebook(cells=[new_code_cell("b = 5")])
    nb.metadata["stylesheet"] = [
        "https://example.com/style1.css",
        "https://example.com/style2.css",
    ]

    output, resources = exporter.from_notebook_node(nb)

    # Parse HTML and find link tags
    soup = _parse_html(output)

    assert output is not None

    # Find all stylesheet links
    link_tags = soup.find_all("link", rel="stylesheet")
    stylesheet_urls = [link.get("href") for link in link_tags]

    assert "https://example.com/style1.css" in stylesheet_urls, "First stylesheet link not found"
    assert "https://example.com/style2.css" in stylesheet_urls, "Second stylesheet link not found"


def test_generate_notebook_style_block_with_style():
    """Test generating notebook style block with inline CSS."""
    exporter = StyledHTMLExporter()

    notebook_styles = {"style": "body { background: white; }"}
    style_block = exporter._generate_notebook_style_block(notebook_styles)

    # Parse the generated style block
    soup = _parse_html(style_block)

    assert "<style>" in style_block

    # Check for the custom notebook styles comment
    style_tags = soup.find_all("style")
    assert len(style_tags) > 0

    has_custom_comment = False
    for style_tag in style_tags:
        if style_tag.string and "Custom notebook styles" in style_tag.string:
            has_custom_comment = True
            assert "body { background: white; }" in style_tag.string
            break

    assert has_custom_comment, "Custom notebook styles comment not found"


def test_generate_notebook_style_block_with_stylesheet():
    """Test generating notebook style block with external stylesheet."""
    exporter = StyledHTMLExporter()

    notebook_styles = {"stylesheet": "https://cdn.example.com/theme.css"}
    style_block = exporter._generate_notebook_style_block(notebook_styles)

    # Parse and find link tags
    soup = _parse_html(style_block)
    link_tags = soup.find_all("link", rel="stylesheet")

    assert len(link_tags) > 0, "No stylesheet link found"
    assert link_tags[0].get("href") == "https://cdn.example.com/theme.css"


def test_generate_notebook_style_block_empty():
    """Test generating notebook style block with no styles."""
    exporter = StyledHTMLExporter()

    notebook_styles = {}
    style_block = exporter._generate_notebook_style_block(notebook_styles)

    assert style_block == ""


def test_embed_images_enabled_by_default():
    """Test that embed_images is enabled by default."""
    exporter = StyledHTMLExporter()

    assert exporter.embed_images is True


def test_embed_images_can_be_disabled():
    """Test that embed_images can be explicitly disabled."""
    exporter = StyledHTMLExporter(embed_images=False)

    assert exporter.embed_images is False


def test_embed_images_with_markdown_image():
    """Test that markdown images are embedded when embed_images is True."""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create test notebook with image
        nb_path = _create_notebook_with_image(tmpdir)

        # Export with default settings (embed_images=True)
        exporter = StyledHTMLExporter()
        output, resources = exporter.from_filename(nb_path)

        # Parse HTML and find img tags
        soup = _parse_html(output)
        img_tags = soup.find_all("img")

        # Verify image is embedded as data URI
        assert "data:image/png;base64," in output
        # Verify that at least one img tag has a data URI
        has_data_uri = False
        for img in img_tags:
            src = img.get("src", "")
            if src.startswith("data:image/png;base64,"):
                has_data_uri = True
                break

        assert has_data_uri, "No img tag with data URI found"

        # Verify file reference is NOT present (replaced with data URI)
        assert 'src="test.png"' not in output


def test_embed_images_disabled_keeps_file_reference():
    """Test that markdown images remain as file references when embed_images is False."""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create test notebook with image
        nb_path = _create_notebook_with_image(tmpdir)

        # Export with embed_images=False
        exporter = StyledHTMLExporter(embed_images=False)
        output, resources = exporter.from_filename(nb_path)

        # Verify file reference is present
        assert 'src="test.png"' in output, "File reference to test.png not found in output"
